---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Container Setup"
      solveButton: false
    - name: module-02
      label: "Query"
      solveButton: false
    - name: module-03
      label: "Query"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty_rhel/ssh/root
