---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Container Setup"
      solveButton: false
    - name: module-02
      label: "Query"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty_rhel/ssh/root
  - name: "Asciidoc Doc"
    url: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
    external: true
